<!DOCTYPE html>
<html lang='en'>

<?php
/**
 * index.php: Display a single page, that contains sections
 * When viewed in a browser or on a tablet, show the sections
 * When viewed on a smart phone, show a menu button and the introduction
 */
$pageTitle = 'phoneMenu';
$newIncludePath = get_include_path() . ":php";
set_include_path( $newIncludePath );
include_once 'filenames.php';
//
// Instantiate an IdMyGadget object and use it to determine key factors about 
// the device accessing the page.
//
$newIncludePath = get_include_path() . ":idMyGadget";
set_include_path( $newIncludePath );
include_once 'Tera-Wurfl/wurfl-dbapi/TeraWurfl.php';
require_once 'php/deviceData.php';
require_once 'php/IdMyGadget.php';

$debugging = FALSE;
// $allowOverridesInUrl = FALSE;
$allowOverridesInUrl = TRUE;
$idMyGadget = new IdMyGadget( $debugging, $allowOverridesInUrl );
$deviceData = $idMyGadget->getDeviceData();
$gadgetType = $deviceData["gadgetType"];
$gadgetModel = $deviceData["gadgetModel"];
$gadgetBrand = $deviceData["gadgetBrand"];

if ( $gadgetType === GADGET_TYPE_DESKTOP_BROWSER )
{
	$gadgetString = "Desktop Browser";
	$styleSheetName = STYLE_SHEET_DESKTOP;
	$deviceJsFile = JS_DEVICE_DESKTOP;
}
else if ( $gadgetType === GADGET_TYPE_TABLET )
{
	$gadgetString = "Tablet";
	$styleSheetName = STYLE_SHEET_TABLET;
	$deviceJsFile = JS_DEVICE_TABLET;
}
else if ( $gadgetType === GADGET_TYPE_PHONE )
{
	if ( $gadgetModel === GADGET_MODEL_APPLE_PHONE )
	{
		$gadgetString = "iPhone";
		$styleSheetName = STYLE_SHEET_APPLE_PHONE;
		$deviceJsFile = JS_DEVICE_APPLE_PHONE;
	}
	else
	{
		$gadgetString = "Android Phone";
		$styleSheetName = STYLE_SHEET_ANDROID_PHONE;
		$deviceJsFile = JS_DEVICE_ANDROID_PHONE;
	}
}

print '<head>';
print '<title>' . $pageTitle . '</title>';
print '<link rel="stylesheet" type="text/css" ' .
		'href="' . STYLE_SHEET_DIRECTORY . STYLE_SHEET_ALL_DEVICES . '" />';

if ( $styleSheetName === STYLE_SHEET_DESKTOP )
{
	print '<link rel="stylesheet" type="text/css" ' .
			'href="' . STYLE_SHEET_DEVICE_DIRECTORY . STYLE_SHEET_DESKTOP . '" ' .
			'media="screen and (min-width: 481px)" ' .
			'/>' . "\n";
}
elseif ( $styleSheetName === STYLE_SHEET_APPLE_PHONE )
{
	print '<meta name="viewport" content="user-scalable=no, width=device-width" />';
	print '<link rel="stylesheet" type="text/css" ' .
			'href="' . STYLE_SHEET_DEVICE_DIRECTORY . STYLE_SHEET_APPLE_PHONE . '" ' .
		//  'media="only screen and (max-width: 480px)" ' .
			'/>';
}
elseif ( $styleSheetName === STYLE_SHEET_ANDROID_PHONE )
{
	print '<meta name="viewport" content="user-scalable=no, width=device-width" />';
	print '<link rel="stylesheet" type="text/css" ' .
			'href="' . STYLE_SHEET_DEVICE_DIRECTORY . STYLE_SHEET_ANDROID_PHONE . '" ' .
		//  'media="only screen and (max-width: 600px)" ' .
			'/>';
}
else   // presumably a tablet
{
	print '  <link rel="stylesheet" type="text/css" ' .
			'href="' . STYLE_SHEET_DIRECTORY . STYLE_SHEET_REVERSE_COLORS . '" />';
	print '  <link rel="stylesheet" type="text/css" ' .
			'href="' . STYLE_SHEET_DEVICE_DIRECTORY . $styleSheetName . '" />';
}
//
// TODO: Care about IE someday
//
print '<!--[if IE]>';
print '<link rel="stylesheet" type="text/css" href="explorer.css" media="all" />';
print '<![endif]-->';

print '<script type="text/javascript" src="js/lib/jquery.js"></script>';
print '<script type="text/javascript" src="' . JS_DIRECTORY . JS_ALL_DEVICES . '"></script>';
print '<script type="text/javascript" src="' . JS_DEVICE_DIRECTORY . $deviceJsFile . '"></script>';
print '<script type="text/javascript" src="' . JS_DIRECTORY . 'Sections.js"></script>';
print '<script type="text/javascript" src="' . JS_DIRECTORY . 'Content.js"></script>';
?>

<!-- ====================================================================== -->
<!-- Everything in div #content is generated by JavaScript using handlebars -->
<!-- ====================================================================== -->
<script type="text/javascript" src="js/lib/handlebars.js"></script>
<script id="paragraph-section-template" type="text/x-handlebars-template">
	<div id="{{id}}" class="section hide">
		<h2>{{title}}</h2>
		<p>{{{content}}}</p>
	</div>
</script>
<script id="paragraph-list-section-template" type="text/x-handlebars-template">
	<div id="{{id}}" class="section hide">
		<h2>{{title}}</h2>
		{{#each content}}
			<p>{{{text}}}</p>
		{{/each}}
	</div>
</script>
<script id="bullet-list-section-template" type="text/x-handlebars-template">
	<div id="{{id}}" class="section hide">
	<h2>{{title}}</h2>
		<ul>
			{{#each bulletPoints}}
				<li>
					{{#if linkHref}}
						<a class="linkHref" href="{{linkHref}}" target="_blank">{{linkText}}</a>
					{{/if}}
					{{#if bold}}
						<span class="bold">{{bold}}</span>
					{{/if}}
					{{text}}
				</li>
			{{/each}}
		</ul>
	</div>
</script>
<?php  if ( $gadgetType === GADGET_TYPE_PHONE ): ?>
	<script id="phone-menu-template" type="text/x-handlebars-template">
		<div id="phone-menu" class="section">
			<ul>
				{{#each sections}}
					<li><a onClick="showOnlySection('{{id}}')">{{option}}</a>
					</li>
				{{/each}}
			</ul>
		</div><!-- phone-menu -->
	</script>
<?php  endif ?>
</head>

<body>
	<div id="container">
		<div id='header'>
		<?php if ( $gadgetType === GADGET_TYPE_PHONE ): ?>
			<h1><a href='./'><?php echo $gadgetString ?></a></h1>
		<?php elseif ( $gadgetType === GADGET_TYPE_DESKTOP_BROWSER ): ?>
			<h1><?php echo $pageTitle ?> Template</h1>
			<p>It looks like you are using a desktop browser.</p>
		<?php else: ?>
			<h1><?php echo $pageTitle ?> </h1>
			<p>It looks like you are using a tablet.</p>
		<?php endif; ?>
		</div>  <!-- header -->

		<div id="content">
			<!-- Everything in div #content is generated by JavaScript using handlebars -->
		</div>  <!-- content -->

	</div> <!-- container -->
</body>
</html>
